# https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
apiVersion: v1
kind: Pod
metadata:
  name: pod-06-limit-mem
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pod-limits
spec:
  containers:
  - name: mem-demo
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-06-limit-mem-acima
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pod-limits
spec:
  containers:
  - name: mem-demo
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
---
# https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
apiVersion: v1
kind: Pod
metadata:
  name: pod-06-limit-cpu
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pod-limits
spec:
  containers:
  - name: cpu-demo
    image: vish/stress
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "500m"
    args:
    - -cpus
    - "2"