# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1-pv-5mi
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pv-persistentvolume
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: nfs.k8s.cluster
    path: "/mnt/nfs/nfs1"
  mountOptions:
    - hard
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1-pv-20mi
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pv-persistentvolume
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: nfs.k8s.cluster
    path: "/mnt/nfs/nfs2"
  mountOptions:
    - hard
    - nfsvers=4.2