apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs1-pvc-teste
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pvc-persistentvolumeclaim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs1-pvc-html
  namespace: exemplos
  labels:
    app: vagrant-k8s-cluster
    exemplo: pvc-persistentvolumeclaim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi